### ISSUE TITLE
Liste aaler Karten pro Spieler

### ISSUE THREAD

**Issue by Spinalzo** [Spinalzo/legends-league#10]
@Fabulit 

Das wäre der erste Nach-Live Task.

Für weitere gute und auch skurille Listen bin ich immer dankbar. :-)

Lass uns die Welt mit Statistiken vollfuttern...

**Comment by Fabulit** [comment]
Unter api.php/cardsList bekommst Du eine Liste aller Karten, die Du selbst nach Spieler filtern könntest. Oder unter api.php/cardsList/2 bekommst Du alle Karten von dem Spieler mit der Id 2.

**Comment by Fabulit** [comment]
Allerdings wird der Name der Karte noch nicht in der Liste geführt :(

**Comment by Spinalzo** [comment]
Naja... Jetzt bin ich mal gespannt, wie die Außenwelt auf den wahnsii reagieren wird. Außer uns beiden weiß ja niemand, was das fürn Kracher ist ;-)

**Comment by Spinalzo** [comment]
Done
