### ISSUE TITLE
Tabellen-Darstellung im IE11

### ISSUE THREAD

**Issue by Fabulit** [Spinalzo/legends-league#4]
@Spinalzo Vermutlich nicht wie gewünscht ;)

![tabellen im ie11](https://cloud.githubusercontent.com/assets/22505648/19625519/34633226-991b-11e6-8cf5-626a395f6469.jpg)

**Comment by Spinalzo** [comment]
Wohl gelöst. Die IE-Spießer jubilieren. Die Freiheit trauert.
