### ISSUE TITLE
Results delete

### ISSUE THREAD

**Issue by Spinalzo** [Spinalzo/legends-league#6]
Im angemeldeten Zustand kannst du auf der Resultliste neben den Spielen ein Kreuzchen sehen. Darauf muss eine Funktion zum Löschen des daneben stehenden Matches aufgerufen werden können. Diese Funktion fehlt mir noch.

**Comment by Fabulit** [comment]
@Spinalzo 
Was hindert Dich daran, eine solche Funktion zu schreiben? Du hast doch eine Funktion zum Spieler löschen, oder nicht? Nimm die als Vorlage. Löschen ist viel einfacher als Erstellen. Das bekommst Du hin.

Hinweis: Du musst nur den Eintrag in tbl_game löschen, alle verknüpften Votes und Ratings sollten automatisch gelöscht werden.

**Comment by Spinalzo** [comment]
Mein größtes Problem dabei ist, dass es keine ID gibt, auf die zurückgreifen kann. Die Resultate entstammen der resultsList.

Aber ich werde mich erst einmal versuchen.

**Comment by Fabulit** [comment]
Ich werde Dir die gameId mit in die resultsList legen. Das ist kein Problem

**Comment by Spinalzo** [comment]
Na saueber... ich war schon bereit, dafür Verbrechen zu begehen... ;-)

**Comment by Spinalzo** [comment]
Das schmeißt leider einen Fehler:

http://gurkaleague.de/legendsleague/app/api.php/resultsList

Fatal error: Call to a member function execute() on a non-object in /var/www/web128013/html/legendsleague/app/api.php on line 25

**Comment by Fabulit** [comment]
Mist, ich schau mal

**Comment by Spinalzo** [comment]
Ich habe nochmal mit allem rumgespielt. Da scheint etwas grundsätzlich nicht zu klappen. Also es muss nicht unbedingt an deinen letzten Änderungen liegen.

Ich habe die bisherige funktionierende DB mal gelöscht (aber ein Backup angelegt). Mit der neuen  leeren Datenbank kam es auch bei der alten (scheinbar noch funktionierenden) createTables zu folgender Fehlermeldung; VM742:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0.

http://gurkaleague.de/legendsleague/app/api.php/datablob wirft den gleichen Fehler, den ich vorhin gemeldet habe. Also auch ohne deine Änderungen.

Fatal error: Call to a member function execute() on a non-object in /var/www/web128013/html/legendsleague/app/api.php on line 25

Was weiterhin funktioniert ist das Erstellen von Ergebnissen.

Welche Kombo vollständig klappt:

Alte DB + alte createTables (diesen Stand habe ich jetzt erst einmal auf live wieder so eingerichtet)

**Comment by Spinalzo** [comment]
done

**Comment by Fabulit** [comment]
Juhu!
